env:
    credentials: "ENCRYPTED[!27a6cc4b75e4efbb734dd1516c19007e132c0ac3aca874a6aba831a04c55e35d2baef260749943a15b995a4115796c1d!]"
    rcloneconfig: "ENCRYPTED[!bb2832906c58d01338e8b1e7de44ec13eeb68571a2c88ca6dfb4605eee66ae026befa372aa12a14154dfece241256e54!]"
    tokentl: "ENCRYPTED[!a78bd3935d8fe05e7332e0a0d18ec5bfe6fe38dfeb0f8f2be03c39caa5165d1f1122c4c652f2c898599737a3fdcc03bf!]"
    idtl: "ENCRYPTED[!fad34f452ed9a692c32548b41cb9521f78b81edd6e7a0ece89110c2b0893d69c788f5eb03c746068ce587e1ad2d9adbc!]"
    lunch : lunch nad_ysl-userdebug
    make: make nad
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "Rahmad Adi Pratama"
       - git config --global user.email "OhMyVenyx@proton.me"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy venyx:nad-12/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
#      - mkdir -p ~/rom
#      - cd ~/rom
#      - rm -rf * .repo
      - mkdir -p ~/.anu
      - export PATH="~/.anu:$PATH"
      - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.anu/repo
      - chmod a+x ~/.anu/repo
      - git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/OhMyVenyx/android_manifest -b 12.1 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/IDN-Labs/local_manifest --depth 1 -b nad-12.1 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="venyx"
      - export BUILD_HOSTNAME="IDN-Labs"
      - export BUILD_WITH_COLORS=1
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd out/target/product/ysl/ && ls Nusantara*.zip)"
#      - rclone copy out/target/product/ysl/Nusantara*.zip venyx:ysl -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd out/target/product/ysl/ && ls Nusantara*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz venyx:nad-12 -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
